import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Harmonize Getting Started :)</title>
        <meta name="description" content="" />
        <meta name="viewport" content="" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          src="/../../ourImages/download-2.jpg"
          alt="Music Theme"
          width={300}
          height={400}
          // layout="responsive"
        />
        <h1 style={{ color: "#ff4081" }}>Harmonize!</h1>
        <p
          className={styles.description}
          style={{ borderBottom: "2px solid #ff4081" }}
        >
          Discover your musical soulmate by selecting your favorite playlists,
          songs, and artists.
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image
              src="/../../ourImages/images-1.jpg"
              width={100}
              height={100}
            />
            <h2 style={{ color: "#0070f3" }}>Select Playlists &rarr;</h2>
            <p>
              Choose your playlists you want to share so you can find matches
              with similar tastes.
            </p>
            <ul>
              <li>Chill Vibes</li>
              <li>Workout Energy</li>
              <li>Cafe Music</li>
            </ul>
          </div>
          <div className={styles.card}>
            <Image
              src="/../../ourImages/images-2.jpg"
              width={100}
              height={100}
            />
            <h2 style={{ color: "#00e676" }}>Select Songs &rarr;</h2>
            <p>
              Pick your top songs to share your daily vibes with potential
              matches.
            </p>
            <ul>
              <li>Song A - Artist 1</li>
              <li>Song B - Artist 2</li>
              <li>Song C - Artist 3</li>
            </ul>
          </div>
          <div className={styles.card}>
            <Image
              src="/../../ourImages/images-3.jpg"
              width={100}
              height={100}
            />
            <h2 style={{ color: "#ff5252" }}>Select Artists &rarr;</h2>
            <p>
              Choose your favorite artists to match with others who like them as
              well.
            </p>
            <ul>
              <li>Artist 1</li>
              <li>Artist 2</li>
              <li>Artist 3</li>
            </ul>
          </div>
        </div>

        <div className={styles.footer}>
          <p style={{ color: "#673ab7" }}>
            Start your journey and find your musical match today!
          </p>

          <Link legacyBehavior href="/picturechoose">
            <a style={{ color: "#0070f3" }}>
              Click Here to Select Your Photos!{" "}
            </a>
          </Link>

          <Link legacyBehavior href="/susanIndex">
            <a style={{ color: "#0070f3" }}>Susanindex</a>
          </Link>
        </div>
      </main>
    </>
  );
}

/*

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}

*/
